name: Validate JSON

on: [pull_request, push]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Validate JSON
        run: find . -name "*.json" -exec jq empty {} \;
