name: Validate JSON Files

on: [push, pull_request]

jobs:
  json-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Validate JSON files
        run: |c
          for file in $(find . -type f -name "*.json"); do
            if ! jq empty "$file"; then
              echo "❌ Invalid JSON: $file"
              exit 1
            fi
          done
          echo "✅ All JSON files are valid."
